// Writes ios/Runner/Secrets.swift with the thermal imager's factory Wi-Fi
// password. The file is gitignored; run this once per machine before
// building the iOS app:
//
//   dart run tool/set_wifi_password.dart
//
// The password is asked for in the terminal with echo off and stored
// XOR-encoded, so it does not show up in `strings` on the binary. This is
// hiding, not protection: anyone with the IPA and a disassembler can still
// recover it. The Android build does not contain the password at all: there
// the user joins the network through the system Wi-Fi panel.
import 'dart:convert';
import 'dart:io';
import 'dart:math';

const String outputPath = 'ios/Runner/Secrets.swift';

void main() {
  if (!Directory('ios/Runner').existsSync()) {
    stderr.writeln('Run this from the project root (ios/Runner not found).');
    exit(2);
  }

  final password = _readPassword();
  if (password.length < 8 || password.length > 63) {
    stderr.writeln(
      'A WPA2 password is 8 to 63 characters; got ${password.length}.',
    );
    exit(1);
  }

  final data = utf8.encode(password);
  final random = Random.secure();
  final key = List<int>.generate(data.length, (_) => random.nextInt(256));
  final encoded = [for (var i = 0; i < data.length; i++) data[i] ^ key[i]];

  File(outputPath).writeAsStringSync(_swiftSource(key, encoded));
  stdout.writeln('Wrote $outputPath.');
}

String _readPassword() {
  stdout.write('Thermal imager Wi-Fi password (not echoed): ');
  final interactive = stdin.hasTerminal;
  final hadEcho = interactive ? stdin.echoMode : true;
  String? line;
  try {
    if (interactive) stdin.echoMode = false;
    line = stdin.readLineSync(encoding: utf8);
  } finally {
    if (interactive) stdin.echoMode = hadEcho;
  }
  stdout.writeln();
  return (line ?? '').trim();
}

String _swiftSource(List<int> key, List<int> encoded) {
  final header = r'''
// Generated by tool/set_wifi_password.dart. Not committed (see .gitignore).
// Holds the thermal imager's factory Wi-Fi password, XOR-encoded so it is
// not visible to `strings`. Run the tool again to change it.

enum Secrets {
''';
  final footer = r'''

  static var archerWifiPassword: String {
    String(decoding: zip(d, k).map { $0 ^ $1 }, as: UTF8.self)
  }
}
''';
  return '$header'
      '  private static let k: [UInt8] = [${key.join(', ')}]\n'
      '  private static let d: [UInt8] = [${encoded.join(', ')}]\n'
      '$footer';
}
